"use client";

import React from "react";
import type { NextPage } from "next";
import ImageGallery from "~~/components/ImageGallery";

const Home: NextPage = () => {
  const images = [
    {name: "Africa Arts", description: "African art is incredibly diverse, reflecting the rich cultural heritage of the continent. It encompasses everything from sculptures and masks to textiles, beadwork, pottery, and body art. \nMany African art forms have a strong functional purpose besides aesthetics. Masks might be used in rituals, sculptures might depict ancestors or deities, and textiles could serve as clothing or social status symbols.", src:"https://bafybeibasfytwjurr7ois7mldbehdqt7ce74q2xojefr23rccazfvwc34e.ipfs.dweb.link/1.jpeg", },
    {name: "Beyond patterns", description: "African art forms frequently use patterns that hold symbolic meaning.  These patterns go beyond simple decoration and can represent proverbs, beliefs, or social structures. For instance, some cultures may have specific geometric patterns that represent strength, fertility, or balance. African art is not static, and there is a constant push for innovation alongside the preservation of traditions. Artists incorporate new materials, techniques, and styles while referencing and reinterpreting established art forms.", src:"https://bafybeibasfytwjurr7ois7mldbehdqt7ce74q2xojefr23rccazfvwc34e.ipfs.dweb.link/2.jpeg", },
    {name: "A picture is worth a thousand words", description: "Many African cultures have strong traditions of storytelling and passing down knowledge through oral traditions. Since stories can be long and complex, visual aids like sculptures, masks, and paintings play a crucial role in conveying information and history. African art is rife with symbolism. A single carving or statue can communicate numerous ideas or stories through its posture, clothing, facial expressions, and objects depicted. The three-headed woman statue itself is a good example. Without any words, it provokes questions and invites interpretation. The three heads could represent  multiple things depending on the culture. It could represent different aspects of a deity,  wisdom gained through experience (seeing things from multiple perspectives), or the past, present, and future.", src:"https://bafybeibasfytwjurr7ois7mldbehdqt7ce74q2xojefr23rccazfvwc34e.ipfs.dweb.link/3.jpeg", },
    {name: "Folktales", description: "Storytelling is a central part of African cultures and traditions. Folktales are passed down through generations, often orally, serving as a way to educate younger generations about cultural values, moral lessons, and history. African folktales cover a wide range of themes, including creation myths, trickster tales, and stories about ancestors and spirits. Animals often play a significant role in these stories, representing human strengths and weaknesses or serving as moral exemplars.", src: "https://bafybeibasfytwjurr7ois7mldbehdqt7ce74q2xojefr23rccazfvwc34e.ipfs.dweb.link/4.jpeg", selected: false},
    {name: "Africa's Creating Force", description: "Women often play a central role in keeping traditions alive by passing down folktales, songs, and proverbs through oral narratives. These stories are not just entertainment; they act as repositories of cultural values, history, and lessons for future generations. Many traditional art forms like textile weaving, beadwork, pottery, and basket making are primarily practiced by women. These skills are passed down through mothers and daughters, ensuring the continuity of artistic styles and techniques.Many women in Africa are entrepreneurs, using their skills in textile making, fashion design, and other crafts to create businesses and support their families.", src:"https://bafybeibasfytwjurr7ois7mldbehdqt7ce74q2xojefr23rccazfvwc34e.ipfs.dweb.link/5.webp", },
    {name: "More than a Statue", description: "In many African cultures, statues serve a purpose beyond decoration or commemoration. They may represent ancestors, deities, or spirits. These statues are often imbued with spiritual significance and are seen as a way to connect with the living and the dead. 'More than a statue' acknowledges this deeper meaning. It emphasizes that respect should not be given solely to the physical statue itself, but rather to what it represents in the larger cultural and spiritual context.", src:"https://bafybeibasfytwjurr7ois7mldbehdqt7ce74q2xojefr23rccazfvwc34e.ipfs.dweb.link/6.jpeg", },
    {name: "A thousand words in a single picture", description: "Nsibidi is a complex system of graphic symbols used by the Igbos. These symbols can represent sounds, words, ideas, or proverbs.  A single symbol can have multiple meanings depending on the context. Nsibidi is not simply a phonetic writing system; it is a way of conveying complex messages and ideas in a concise and nuanced way.  Because of this, a single nsibidi symbol or image can hold a lot of meaning. Understanding the full meaning of nsibidi symbols requires knowledge of Igbo culture, history, and the context in which the symbols are used.", src:"https://bafybeibasfytwjurr7ois7mldbehdqt7ce74q2xojefr23rccazfvwc34e.ipfs.dweb.link/7.jpg", },
    {name: "A Kingdom that lives on", description: "The crown on the figure’s head is a clear symbol of royalty and power in many African cultures.  Headwear, especially elaborate crowns, were often used to distinguish rulers and elites from the rest of the population. The image shares some stylistic similarities with the art of the Benin Kingdom, which was a powerful state in West Africa from the 14th to the 19th centuries.  Benin art is known for its use of bronze casting and for its depiction of human figures and royalty. The crown also has similarities to those worn by the Yoruba people of Nigeria.  Yoruba art also frequently depicts human figures, including kings, queens, and other important figures.", src:"https://bafybeibasfytwjurr7ois7mldbehdqt7ce74q2xojefr23rccazfvwc34e.ipfs.dweb.link/8.jpeg", },
    {name: "Culture passed down as moulded arts", description: "Masks are a prominent art form in many African cultures. They are used in a variety of rituals, ceremonies, and performances.  Masks may represent spirits, ancestors, or specific characters. The creation of masks is often a community endeavor, passed down from elders to younger generations.  This ensures the survival of traditional techniques and styles.", src:"https://bafybeibasfytwjurr7ois7mldbehdqt7ce74q2xojefr23rccazfvwc34e.ipfs.dweb.link/9.jpeg", },
    {name: "The Land of the Rising Sun", description: "The red cap is a prominent symbol of masculinity and achievement among the Igbo people. Traditionally, only men who achieved a certain level of status or wealth could wear a red cap.  In some communities, the type of red cap may also indicate the wearer’s title or social status. Beaded necklaces, bracelets, and anklets are common accessories in many African cultures, including the Igbos.  Beads can symbolize wealth, social status, or religious beliefs. The  colors and patterns of the beads  may also hold specific meanings. In Igbo culture, clothing and accessories are not just about fashion; they are a way to communicate social status, wealth, achievements, and even religious beliefs. By adorning themselves with these items, Igbo men can visually represent their place in society and their achievements.", src:"https://bafybeibasfytwjurr7ois7mldbehdqt7ce74q2xojefr23rccazfvwc34e.ipfs.dweb.link/10.jpeg", },
  ];

  return (
    <>
      <ImageGallery images={images} />
    </>
  );
};

export default Home;
